name: Feature Request
description: File a feature request.
title: "[Feature Request]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit your feature request!
  - type: textarea
    id: solution-description
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: Describe the solution you'd like here.
    validations:
      required: true
  - type: checkboxes
    id: benefit-to-others
    attributes:
      label: Can others benefit from your feature?
      description: Choose whether others can benefit from this feature.
      options:
        - label: Yes, others can also benefit from this feature.
          required: false
        - label: No, others cannot benefit from this feature.
          required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Provide any additional context or screenshots here.
